version: "3.8"

services:
  web:
    image: webdevops/php-apache:alpine-php7
    ports:
      - "4500:80"
    volumes:
      - /projeto-docker/ControleFinanceiro/:/app
    networks:
      - minha-rede

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "controle_financeiro"
    ports:
      - "3306:3306"
    volumes:
      - /projeto-docker/data/MySQL:/var/lib/mysql
    networks:
      - minha-rede

networks:
   minha-rede:
     driver: bridge
